Updated init script

diff --git a/recipes/tivsm-ba/tivsm-ba.debian/init b/recipes/tivsm-ba/tivsm-ba.debian/init
--- a/recipes/tivsm-ba/tivsm-ba.debian/init
+++ b/recipes/tivsm-ba/tivsm-ba.debian/init
@@ -1,13 +1,9 @@
 #! /bin/sh
 #
-# Author: Christopher Huhn <c.huhn@gsi.de>
-#
-# script for starting  the tsm scheduler during boot
-#
 ### BEGIN INIT INFO
-# Provides:          tsm-ba
-# Required-Start:    $remote_fs 
-# Required-Stop:     $remote_fs
+# Provides:          tsm-scheduler
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: start the TSM client scheduler
@@ -15,80 +11,148 @@
 #                    must be started in scheduler mode and daemonized
 ### END INIT INFO
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DSMC=/usr/lib/tsm-ba/dsmc
-NAME=$(basename $DSMC)
+# Author: Christopher Huhn <c.huhn@gsi.de>
+
+# Do NOT "set -e"
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="TSM scheduler"
+NAME=dsmc
+DAEMON=/usr/bin/$NAME
+DAEMON_ARGS="schedule"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 
-# define default location if not specified elsewhere
-[ $DSM_CONFIG ] || export DSM_CONFIG=/etc/tsm/dsm.opt
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-DSM_DIR=/usr/lib/tsm-ba/
-DSM_LOG=/var/log/tsm/
-# LC_ALL must be set to en_US to backup filenames with non-ASCII characters ?!
-LC_ALL=en_US
-export DSM_DIR DSM_LOG LC_ALL
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-test -x $DSMC || exit 0
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
 
-set -e
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --background \
+	    --make-pidfile --exec $DAEMON -- \
+	    $DAEMON_ARGS \
+	    || return 2
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
+}
 
 case "$1" in
-    
-    start)
-	echo -n "Starting $DESC: $NAME "
-	        # tsmc neither forks to background nor creates a pidfile by itself:
-	start-stop-daemon --start --background \
-	    --make-pidfile --pidfile /var/run/$NAME.pid \
-	    --exec $DSMC -- schedule
-	echo "."
+  start)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
-    
-    stop)
-	echo -n "Stopping $DESC: $NAME "
-	start-stop-daemon --stop --pidfile /var/run/$NAME.pid \
-	    --signal 9 --exec $DSMC \
-	    && rm /var/run/$NAME.pid
-	echo "."
+  stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
-    
-    #reload)
-	# 
-	# If the daemon can reload its config files on the fly
-	# for example by sending it SIGHUP, do it here.
-        #;;
-    
-    restart|force-reload)
-	    #
-     	#	If the "reload" option is implemented, move the "force-reload"
-	    #	option to the "reload" entry above. If not, "force-reload" is
-	    #	just the same as "restart".
-	    # 
-	echo -n "Restarting $DESC: "
-	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
-	    --exec $DSMC || true	
-	echo -n "$NAME"
-	sleep 1
-	start-stop-daemon --start --quiet --background \
-	    --make-pidfile --pidfile /var/run/$NAME.pid \
-	    --exec $DSMC -- schedule
-	echo "."
+  status)
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
 	;;
-    
-    status)
-	if [ -r /var/run/$NAME.pid ] && [ -d /proc/$(cat /var/run/dsmc.pid) ]; then
-	    $DSMC query schedule
-	else
-	    echo "$DESC is not running" >&2
-        fi
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+		# Failed to stop
+		log_end_msg 1
+		;;
+	esac
 	;;
-    
-    *)
-	N=/etc/init.d/$NAME
-	    # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
-	exit 1
+  *)
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
 	;;
 esac
 
-exit 0
+:
