Changes to finish packaging mathlm

diff --git a/debutant b/debutant
--- a/debutant
+++ b/debutant
@@ -41,12 +41,22 @@ add_dependency() {
     done
 }
 
-add_init_script() {
+add_initscript() {
     local init=$1
     [ "$init" ] || init=$RECIPE_DIR/init
     cp "$init" $PKG_DIR/debian/init
-    # modern initscripts make use of lsb functions:
+    # also copy over the default file if found:
+    [ -e `dirname $init`/default ] && cp `dirname $init`/default $PKG_DIR/debian/default
+    # 'modern' initscripts make use of lsb functions:
     #add_dependency "lsb-base (>= 3.2-14)" # versioned depends not supported by add_dependency yet
+}
+
+add_install_scripts() {
+    for file in preinst postinst prerm postrm; do
+        [ -e $RECIPE_DIR/$file ] || continue
+        cp $RECIPE_DIR/$file $PKG_DIR/debian/
+        chmod a+rx $PKG_DIR/debian/$file
+    done
 }
 
 # sometimes we want to build i386 packages on amd64
@@ -232,10 +242,24 @@ for D in $RECIPE_DIRS; do
         set -e
         [ $DEBUG ] && set -x
         
+        RECIPE_DIR=`dirname $0`/recipes/$RECIPE
+
         # preparations are performed here, not inside recipes
         prepare
-        RECIPE_DIR=`dirname $0`/recipes/$RECIPE
+        # now we have a BUILD_DIR
+        # stage 1: extract and convert the archive
         . $RECIPE_DIR/recipe $@
+        #. $RECIPE_DIR/recipe extract 1$@
+        
+        # now we have a PKG_DIR and put debian/... into it:        
+        #dh_make ... #preseeded with recipe config?
+        #cp -b $RECIPE_DIR/debian/* $PKG_DIR/debian/
+        
+        # stage 2: customize debian files:
+        #. $RECIPE_DIR/recipe package $@
+        
+        # stage 3: we build the package and clean up
+        
         if [ $DEBUG ]; then
             set +x
         else
diff --git a/recipes/mathlm/init b/recipes/mathlm/init
--- a/recipes/mathlm/init
+++ b/recipes/mathlm/init
@@ -40,8 +40,8 @@ MATHPASS=/etc/mathlm/mathpass
 do_start()
 {
     if [ ! -r "$MATHPASS" ]; then
-	log_daemon_msg "No mathpass file found, not starting mathlm"
-	return 2
+	    log_daemon_msg "No mathpass file found, not starting mathlm"
+	    return 2
     fi
     
 	# Return
@@ -49,12 +49,12 @@ do_start()
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
     start-stop-daemon --start --quiet --pidfile $PIDFILE \
-	--exec $DAEMON --test > /dev/null \
-	|| return 1
-    start-stop-daemon --start --background --quiet --make-pidfile --chuid  nobody:nogroup \
-	--pidfile $PIDFILE --exec $DAEMON \
-	-- $DAEMON_ARGS -pwfile $MATHPASS  -foreground \
-	|| return 2
+	    --exec $DAEMON --test > /dev/null \
+	    || return 1
+    start-stop-daemon --start --background --quiet --make-pidfile --chuid mathlm:mathlm \
+	    --pidfile $PIDFILE --exec $DAEMON \
+	    -- $DAEMON_ARGS -pwfile $MATHPASS  -foreground \
+	    || return 2
 	# Add code here, if necessary, that waits for the process to be ready
 	# to handle requests from services started subsequently which depend
 	# on this one.  As a last resort, sleep for some time.
@@ -79,7 +79,7 @@ do_stop()
 	# that waits for the process to drop all resources that could be
 	# needed by services started subsequently.  A last resort is to
 	# sleep for some time.
-
+    
     start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
 	[ "$?" = 2 ] && return 2
 	# Many daemons don't delete their pidfiles when they exit.
@@ -101,29 +101,29 @@ do_reload() {
 }
 
 case "$1" in
-  start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-	do_start
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
-  stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
-  status)
-	if status_of_proc "$DAEMON" "$NAME"; then
-	    exit 0 
-	else 
-	    exit $?
-	fi
-	;;
+    start)
+	    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	    do_start
+	    case "$?" in
+		    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	    esac
+	    ;;
+    stop)
+	    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	    do_stop
+	    case "$?" in
+		    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	    esac
+	    ;;
+    status)
+	    if status_of_proc "$DAEMON" "$NAME"; then
+	        exit 0 
+	    else 
+	        exit $?
+	    fi
+	    ;;
   #reload|force-reload)
 	#
 	# If do_reload() is not implemented then leave this commented out
@@ -133,33 +133,33 @@ case "$1" in
 	#do_reload
 	#log_end_msg $?
 	#;;
-  restart|force-reload)
+    restart|force-reload)
 	#
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
 	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
+	    log_daemon_msg "Restarting $DESC" "$NAME"
+	    do_stop
+	    case "$?" in
+	        0|1)
+		        do_start
+		        case "$?" in
+			        0) log_end_msg 0 ;;
+			        1) log_end_msg 1 ;; # Old process is still running
+			        *) log_end_msg 1 ;; # Failed to start
+		        esac
+		        ;;
+	        *)
 		# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
-  *)
+		        log_end_msg 1
+		        ;;
+	    esac
+	    ;;
+    *)
 	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-	exit 3
-	;;
+	    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	    exit 3
+	    ;;
 esac
 
 :
